language: python
python:
  - "2.7"
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=isort
  - TOXENV=flake8

install:
    - pip install tox

script: tox -e $TOXENV

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django110
    - python: 3.5
      env: TOXENV=flake8
